// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaqKJQFyAI-_danZxHpIuupoaRevCFiYU',
    appId: '1:561708302101:web:564e8f84660a9aeb87731c',
    messagingSenderId: '561708302101',
    projectId: 'geekfind01',
    authDomain: 'geekfind01.firebaseapp.com',
    storageBucket: 'geekfind01.firebasestorage.app',
    measurementId: 'G-D5JB2TL2NY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsmq6hjEEgZvqNVLWcWFXgfMxV8a84xTU',
    appId: '1:561708302101:android:99d9f606f1c7991287731c',
    messagingSenderId: '561708302101',
    projectId: 'geekfind01',
    storageBucket: 'geekfind01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOeSNtpTjVty0ZNR5L9739rEM7y1NvQQs',
    appId: '1:561708302101:ios:deefc48a4e6b907987731c',
    messagingSenderId: '561708302101',
    projectId: 'geekfind01',
    storageBucket: 'geekfind01.firebasestorage.app',
    iosBundleId: 'com.manuelamb.geekfindprojeto.geekFindProjeto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOeSNtpTjVty0ZNR5L9739rEM7y1NvQQs',
    appId: '1:561708302101:ios:deefc48a4e6b907987731c',
    messagingSenderId: '561708302101',
    projectId: 'geekfind01',
    storageBucket: 'geekfind01.firebasestorage.app',
    iosBundleId: 'com.manuelamb.geekfindprojeto.geekFindProjeto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaqKJQFyAI-_danZxHpIuupoaRevCFiYU',
    appId: '1:561708302101:web:15c065e6c582de7c87731c',
    messagingSenderId: '561708302101',
    projectId: 'geekfind01',
    authDomain: 'geekfind01.firebaseapp.com',
    storageBucket: 'geekfind01.firebasestorage.app',
    measurementId: 'G-0EYPE60M5P',
  );
}
